#!/usr/bin/env python3
"""Turn the Canvas announcements Atom feed into announcements.js.

The feed URL is an enrollment-scoped secret: anyone holding it can read the
course's announcements. It is therefore read from the CANVAS_FEED_URL
environment variable and never written into the generated file or committed.

Usage:  CANVAS_FEED_URL='https://…' python3 scripts/fetch_announcements.py
"""
import html
import json
import os
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime
from html.parser import HTMLParser

NS = {'a': 'http://www.w3.org/2005/Atom'}
OUT = os.path.join(os.path.dirname(__file__), '..', 'announcements.js')

# Canvas posts are written by officers in a rich-text editor. Keep the markup
# that carries meaning and drop everything else, so the page never renders
# script, styling, or embedded frames from the feed.
ALLOWED = {
    'p': set(), 'br': set(), 'strong': set(), 'b': set(), 'em': set(),
    'i': set(), 'u': set(), 'ul': set(), 'ol': set(), 'li': set(),
    'blockquote': set(), 'h2': set(), 'h3': set(), 'h4': set(),
    'a': {'href'},
}
VOID = {'br'}


class Sanitizer(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out = []
        self.open = []

    def handle_starttag(self, tag, attrs):
        if tag not in ALLOWED:
            return
        keep = ''
        if tag == 'a':
            href = dict(attrs).get('href', '')
            # Only linkable schemes; no javascript: or data: payloads.
            if not re.match(r'^(https?:|mailto:)', href, re.I):
                href = ''
            if href:
                keep = f' href="{html.escape(href, quote=True)}"' \
                       ' target="_blank" rel="noopener noreferrer"'
        self.out.append(f'<{tag}{keep}>')
        if tag not in VOID:
            self.open.append(tag)

    def handle_endtag(self, tag):
        if tag not in ALLOWED or tag in VOID:
            return
        if tag in self.open:
            while self.open:
                t = self.open.pop()
                self.out.append(f'</{t}>')
                if t == tag:
                    break

    def handle_data(self, d):
        self.out.append(html.escape(d))

    def result(self):
        while self.open:
            self.out.append(f'</{self.open.pop()}>')
        s = ''.join(self.out)
        s = re.sub(r'(?:<p>\s*</p>|<p>(?:&nbsp;|\s)*</p>)', '', s)
        return re.sub(r'\s+\n', '\n', s).strip()


def clean_html(raw):
    s = Sanitizer()
    s.feed(raw)
    s.close()
    return s.result()


def initials(name):
    parts = [p for p in re.split(r'\s+', name.strip()) if p]
    return ''.join(p[0] for p in parts[:2]).upper()


def titlecase(name):
    # Canvas returns author names shouted in caps.
    return ' '.join(w.capitalize() for w in name.split())


def main():
    url = os.environ.get('CANVAS_FEED_URL', '').strip()
    if not url:
        sys.exit('CANVAS_FEED_URL is not set. Refusing to run without the feed '
                 'URL, which must come from the environment and never the repo.')

    with urllib.request.urlopen(url, timeout=60) as r:
        xml_bytes = r.read()

    root = ET.fromstring(xml_bytes)
    posts = []
    for e in root.findall('a:entry', NS):
        title = (e.findtext('a:title', '', NS) or '').strip()
        title = re.sub(r'^Announcement:\s*', '', title)
        author = titlecase((e.findtext('a:author/a:name', '', NS) or '').strip())
        published = (e.findtext('a:published', '', NS) or '').strip()
        link = e.find('a:link', NS)
        href = (link.get('href') if link is not None else '') or ''
        href = href.replace('http://', 'https://')
        body = clean_html(e.findtext('a:content', '', NS) or '')

        try:
            dt = datetime.fromisoformat(published.replace('Z', '+00:00'))
            posted = f'Posted {dt.strftime("%b %-d, %Y")}'
        except ValueError:
            dt, posted = None, ''

        posts.append({
            'id': (e.findtext('a:id', '', NS) or href or title).strip(),
            'title': title,
            'author': author,
            'initials': initials(author),
            'published': published,
            'posted': posted,
            'url': href,
            'html': body,
        })

    posts.sort(key=lambda p: p['published'], reverse=True)

    header = (
        '/* =========================================================================\n'
        '   Announcements mirrored from the chapter\'s Canvas announcements feed.\n'
        '\n'
        '   Generated by scripts/fetch_announcements.py — do not hand-edit. The\n'
        '   feed URL is an enrollment-scoped secret and is deliberately absent\n'
        '   from this file; it lives in the CANVAS_FEED_URL repository secret.\n'
        '   ========================================================================= */\n\n'
        'window.TSA_ANNOUNCEMENTS = '
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(header + json.dumps(posts, ensure_ascii=False, indent=1) + ';\n')

    print(f'wrote {len(posts)} announcements -> announcements.js')
    if posts:
        print(f'newest: {posts[0]["posted"]} — {posts[0]["title"]}')


if __name__ == '__main__':
    main()
